### ISSUE TITLE
Completion of video isn't changing the play button to pause button

### ISSUE THREAD

**Issue by arjunthakur08** [arjun0108/the-eye-video-player#4]
**Play button not changing to pause button** when the video is completely watched.

**Comment by arjun0108** [comment]
**Issue Solved** in the commit - [4dfd283](https://github.com/arjun0108/the-eye-video-player/commit/4dfd283093a0e498d76ca3341f25267ffac46153)

**Comment by arjunthakur08** [comment]
**Issue Solved** in the commit - [4dfd283](https://github.com/arjun0108/the-eye-video-player/commit/4dfd283093a0e498d76ca3341f25267ffac46153)
